import { useEffect, useRef, useState } from "react";
const API="/api"; const headers=()=>({Authorization:`Bearer ${localStorage.getItem('jip_access_token')||''}`});
export function Notifications(){const [items,setItems]=useState<any[]>([]);const [unread,setUnread]=useState(0);async function load(){const r=await fetch(`${API}/communication/notifications`,{headers:headers()});const d=await r.json();if(r.ok){setItems(d.notifications||[]);setUnread(d.unreadCount||0)}}useEffect(()=>{load()},[]);async function read(id:string){await fetch(`${API}/communication/notifications/${id}/read`,{method:'POST',headers:headers()});load()}async function all(){await fetch(`${API}/communication/notifications/read-all`,{method:'POST',headers:headers()});load()}return <section className="list-section"><div className="section-head"><div><p className="eyebrow">INBOX</p><h2>Notifications</h2><p className="section-subtitle">{unread} unread notification{unread===1?'':'s'}.</p></div><button className="secondary-btn" onClick={all}>Mark all read</button></div>{items.length===0?<div className="empty">No notifications yet.</div>:<div className="challenge-list">{items.map(n=><article className={`challenge ${!n.read_at?'notification-unread':''}`} key={n.id}><div className="challenge-top"><span className="tag">{n.type.replaceAll('_',' ')}</span><span className="meta">{new Date(n.created_at).toLocaleString()}</span></div><h3>{n.title}</h3><p>{n.body}</p>{!n.read_at&&<button className="secondary-btn" onClick={()=>read(n.id)}>Mark read</button>}</article>)}</div>}</section>}
export function TranslationView({challengeId}:{challengeId:string|null}){
 const [language,setLanguage]=useState('hi');
 const [translations,setTranslations]=useState<any[]>([]);
 const [busy,setBusy]=useState(false);
 const [error,setError]=useState('');
 async function load(){if(!challengeId)return;const r=await fetch(`${API}/communication/challenges/${challengeId}/translations`,{headers:headers()});const d=await r.json();if(r.ok)setTranslations(d.translations||[])}
 useEffect(()=>{load()},[challengeId]);
 async function translate(){if(!challengeId)return;setBusy(true);setError('');try{const r=await fetch(`${API}/communication/challenges/${challengeId}/translations`,{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({targetLanguage:language})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Translation unavailable');await load()}catch(e){setError(e instanceof Error?e.message:'Translation unavailable')}finally{setBusy(false)}}
 return <section className="list-section translation-workspace"><div className="translation-hero"><div><p className="eyebrow">SMARTSOLVE LANGUAGE ENGINE</p><h2>Translate the complete challenge</h2><p className="section-subtitle">Translate the title, description, location, support type, urgency and available AI analysis together. The original report remains unchanged.</p></div><div className="translation-badge">Full context</div></div>
 {!challengeId?<div className="empty">Select a challenge from My challenges first.</div>:<>
 <div className="translation-toolbar"><label>Target language<select value={language} onChange={e=>setLanguage(e.target.value)}><option value="en">English</option><option value="hi">Hindi</option><option value="bn">Bengali</option><option value="ur">Urdu</option><option value="ta">Tamil</option><option value="te">Telugu</option><option value="sat">Santali</option><option value="nnp">Nagpuri</option></select></label><button className="primary-btn" onClick={translate} disabled={busy}>{busy?'Translating everything…':'Translate everything'}</button></div>
 {error&&<div className="error">{error}</div>}
 <div className="translation-results">{translations.map(t=>{const m=t.translated_metadata||{};const ai=m.ai||{};return <article className="translation-card" key={t.id}><div className="challenge-top"><span className="tag">{t.source_language} → {t.target_language}</span><span className="meta">{t.provider}</span></div><h3>{t.translated_title}</h3><p className="translated-description">{t.translated_description}</p><div className="translated-facts"><div><span>Location</span><b>{m.district||'—'}{m.block?` · ${m.block}`:''}</b></div><div><span>Support</span><b>{m.requestType||'—'}</b></div><div><span>Category</span><b>{m.category||'—'}</b></div><div><span>Urgency</span><b>{m.urgency||'—'}</b></div></div>{ai.summary&&<div className="translated-ai"><strong>AI understanding</strong><p>{ai.summary}</p>{ai.subcategory&&<span>{ai.subcategory}</span>}</div>}{Array.isArray(ai.affected_sectors)&&ai.affected_sectors.length>0&&<div className="chips"><em>{ai.affected_sectors.join(' · ')}</em></div>}<details className="translation-original"><summary>View original report</summary><p><strong>{t.original_title}</strong></p><p>{t.original_description}</p></details></article>})}</div></>}
 </section>
}
export function SOSView(){const [active,setActive]=useState(false);const [seconds,setSeconds]=useState(0);const [location,setLocation]=useState<{latitude:number;longitude:number}|null>(null);const [info,setInfo]=useState('');const [message,setMessage]=useState('');const timer=useRef<number|null>(null);function start(){setActive(true);setSeconds(0);timer.current=window.setInterval(()=>setSeconds(x=>{const next=x+1;if(next>=10){window.clearInterval(timer.current!);timer.current=null;activate();}return next}),1000)}function cancel(){if(timer.current)window.clearInterval(timer.current);timer.current=null;setActive(false);setSeconds(0)}async function activate(){navigator.geolocation.getCurrentPosition(async pos=>{const loc={latitude:pos.coords.latitude,longitude:pos.coords.longitude};setLocation(loc);const r=await fetch(`${API}/sos`,{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({...loc,urgentInformation:info})});const d=await r.json();setMessage(r.ok?`SOS activated. ${d.notifiedOrganizations?.length||0} configured nearby organization(s) were notified.`:(d.error||'SOS could not be activated'));setActive(false)},()=>{setMessage('Location access is required to activate SOS.');setActive(false)},{enableHighAccuracy:true,timeout:10000})}return <section className="list-section"><p className="eyebrow">URGENT RESPONSE</p><h2>SOS</h2><p className="section-subtitle">SOS is separate from normal challenge reporting. Hold the button for 10 seconds; releasing early cancels it. The platform does not claim police or ambulance integration.</p><label>Urgent information<textarea value={info} onChange={e=>setInfo(e.target.value)} maxLength={2000} placeholder="Briefly describe the urgent situation"/></label><div className="sos-box"><button className="sos-button" onMouseDown={start} onMouseUp={cancel} onMouseLeave={cancel} onTouchStart={start} onTouchEnd={cancel}>{active?`HOLDING • ${seconds}/10`:'HOLD SOS FOR 10 SECONDS'}</button><p>{active?'Keep holding until activation. Release before 10 seconds to cancel.':'Only activate for an urgent situation.'}</p></div>{message&&<div className="message">{message}</div>}{location&&<div className="privacy">Location recorded securely for this SOS.</div>}</section>}
export function ProjectMessages({projectId}:{projectId:string|null}){const [messages,setMessages]=useState<any[]>([]);const [text,setText]=useState('');async function load(){if(!projectId)return;const r=await fetch(`${API}/communication/projects/${projectId}/messages`,{headers:headers()});const d=await r.json();if(r.ok)setMessages(d.messages||[])}useEffect(()=>{load()},[projectId]);async function send(){if(!projectId||!text.trim())return;const r=await fetch(`${API}/communication/projects/${projectId}/messages`,{method:'POST',headers:{...headers(),'Content-Type':'application/json'},body:JSON.stringify({message:text})});if(r.ok){setText('');load()}}return <section className="list-section"><p className="eyebrow">PROJECT CHANNEL</p><h2>Project communication</h2><p className="section-subtitle">Only the citizen associated with the challenge and authorized active project participants can access this channel.</p>{!projectId?<div className="empty">Open a project first.</div>:<><div className="message-list">{messages.map(m=><article className="chat-message" key={m.id}><strong>{m.sender_name}</strong><span>{m.sender_role.replaceAll('_',' ')}</span><p>{m.message}</p><small>{new Date(m.created_at).toLocaleString()}</small></article>)}</div><div className="two"><textarea value={text} onChange={e=>setText(e.target.value)} maxLength={5000} placeholder="Write a project update or question"/><button className="primary-btn" onClick={send}>Send message</button></div></>}</section>}
