import type { FormEvent } from "react";
import { useEffect, useState } from "react";
const API="/api";
type Props={token:string};
const districts=['Chatra','Deoghar','Dhanbad','Dumka','East Singhbhum','Garhwa','Giridih','Godda','Gumla','Hazaribagh','Jamtara','Khunti','Koderma','Latehar','Lohardaga','Pakur','Ramgarh','Ranchi','Sahibganj','Seraikela Kharsawan','Simdega','West Singhbhum','Palamu'];
const categories=['education','agriculture','healthcare','water-resources','environment','energy','urban-development','accessibility','public-administration','rural-livelihoods','sanitation','infrastructure','digital-services','disaster-management','waste-management','transportation','other'];
const requests=['technical-consultation','research-project','student-project','field-investigation','field-study','funding','mentorship','prototyping','implementation','testing','technology-transfer','community-project','infrastructure-support','technical-solution'];
const expertise=['civil-engineering','environmental-engineering','water-treatment','water-resources','agriculture','irrigation','agritech','healthcare','public-health','digital-health','education-technology','teacher-training','software','ai','ecology','gis','waste-management','iot','renewable-energy','electrical-engineering','structural-engineering','transportation-engineering','mobility','networking','assistive-technology','accessibility','social-sciences','management','rural-development','urban-planning','public-administration','disaster-management','community-development','problem-solving','infrastructure'];
const types=['COLLEGE','UNIVERSITY','INDUSTRY','STARTUP','MSME','CSR','RESEARCH_LAB','INNOVATION_HUB','COMMUNITY_ORG','PANCHAYAT','ULB','GOVERNMENT_AGENCY'];
const label=(x:string)=>x.replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
function csv(v:string){return v.split(',').map(x=>x.trim()).filter(Boolean)}
export default function Government({token}:Props){
 const h={Authorization:`Bearer ${token}`};
 const [data,setData]=useState<any>(null); const [tickets,setTickets]=useState<any[]>([]); const [selected,setSelected]=useState<any>(null); const [busy,setBusy]=useState(false);
 const [tab,setTab]=useState<'queue'|'overview'|'organizations'|'projects'|'accounts'>('queue'); const [governmentProjects,setGovernmentProjects]=useState<any[]>([]);
 const [showOrg,setShowOrg]=useState(false); const [showUser,setShowUser]=useState(false); const [form,setForm]=useState<any>({name:'',organizationType:'COLLEGE',description:'',district:'',address:'',latitude:'',longitude:'',verified:true,categories:'',expertise:'',requestTypes:''});
 const [userForm,setUserForm]=useState<any>({fullName:'',email:'',password:'',role:'GOVERNMENT',organizationId:'',phone:'',preferredLanguage:'en'});
 async function load(){try{const [a,b,c,pj,u]=await Promise.all([fetch(`${API}/government/dashboard`,{headers:h}),fetch(`${API}/government/challenges?limit=100`,{headers:h}),fetch(`${API}/government/organizations`,{headers:h}),fetch(`${API}/government/projects`,{headers:h}),fetch(`${API}/government/users`,{headers:h})]);const ad=await a.json(),bd=await b.json(),cd=await c.json(),pd=await pj.json(),ud=await u.json();if(a.ok&&b.ok&&c.ok&&pj.ok&&u.ok){setData({...ad,organizations:cd.organizations||[],adminUsers:ud.users||[]});setGovernmentProjects(pd.projects||[]);setTickets(bd.challenges||[]);setSelected((old:any)=>old&&bd.challenges?.find((x:any)=>x.id===old.id)||bd.challenges?.[0]||null)}}catch{}}
 useEffect(()=>{load()},[]);
 async function moderate(id:string,status:string){setBusy(true);try{await fetch(`${API}/government/challenges/${id}/moderation`,{method:'PATCH',headers:{...h,'Content-Type':'application/json'},body:JSON.stringify({status,reason:status==='HIDDEN'?'Hidden by government moderation':''})});await load()}finally{setBusy(false)}}
 async function verify(id:string,verified:boolean){setBusy(true);try{await fetch(`${API}/government/organizations/${id}`,{method:'PATCH',headers:{...h,'Content-Type':'application/json'},body:JSON.stringify({verified})});await load()}finally{setBusy(false)}}
 async function createOrg(e:FormEvent){e.preventDefault();setBusy(true);try{const payload={...form,latitude:form.latitude===''?null:Number(form.latitude),longitude:form.longitude===''?null:Number(form.longitude),district:form.district||null,address:form.address||null,categories:csv(form.categories),expertise:csv(form.expertise),requestTypes:csv(form.requestTypes)};const r=await fetch(`${API}/government/organizations`,{method:'POST',headers:{...h,'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not create institution');setShowOrg(false);setForm({name:'',organizationType:'COLLEGE',description:'',district:'',address:'',latitude:'',longitude:'',verified:true,categories:'',expertise:'',requestTypes:''});await load()}catch(e){alert(e instanceof Error?e.message:'Could not create institution')}finally{setBusy(false)}}
 async function createUser(e:FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch(`${API}/government/users`,{method:'POST',headers:{...h,'Content-Type':'application/json'},body:JSON.stringify({...userForm,organizationId:userForm.organizationId||null,phone:userForm.phone||null})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Could not create account');setShowUser(false);setUserForm({fullName:'',email:'',password:'',role:'GOVERNMENT',organizationId:'',phone:'',preferredLanguage:'en'});await load()}catch(e){alert(e instanceof Error?e.message:'Could not create account')}finally{setBusy(false)}}
 async function setAccount(id:string,active:boolean){setBusy(true);try{await fetch(`${API}/government/users/${id}`,{method:'PATCH',headers:{...h,'Content-Type':'application/json'},body:JSON.stringify({active})});await load()}finally{setBusy(false)}}
 const current=selected?.status||'SUBMITTED';
 if(!data)return <section className="page-panel"><div className="loading-state">Loading command center…</div></section>;
 return <section className="command-center page-panel">
  <div className="command-head"><div><div className="hero-kicker">ADMINISTRATION</div><h1>SmartSolve Command Center</h1><p>Inspect challenges, institutions, projects, users, moderation and impact from one government workspace.</p></div><div className="command-kpis"><span><b>{data.kpis.total_challenges}</b>Reports</span><span><b>{data.kpis.urgent_open}</b>Urgent</span><span><b>{data.kpis.resolved_challenges}</b>Resolved</span><span><b>{data.kpis.active_users}</b>Users</span></div></div>
  <div className="admin-toolbar"><div className="command-tabs"><button className={tab==='queue'?'active':''} onClick={()=>setTab('queue')}>Issue queue</button><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Overview</button><button className={tab==='organizations'?'active':''} onClick={()=>setTab('organizations')}>Institutions</button><button className={tab==='projects'?'active':''} onClick={()=>setTab('projects')}>Projects</button><button className={tab==='accounts'?'active':''} onClick={()=>setTab('accounts')}>Admin accounts</button></div><div className="admin-actions"><button className="secondary-btn" onClick={()=>setShowOrg(true)}>+ Add institution</button><button className="primary-btn small" onClick={()=>setShowUser(true)}>+ Create administrator</button></div></div>
  {tab==='queue'&&<div className="ticket-layout"><aside className="ticket-list">{tickets.map(t=><button key={t.id} className={selected?.id===t.id?'ticket active':'ticket'} onClick={()=>setSelected(t)}><div><span className={`severity ${t.urgency_hint.toLowerCase()}`}>{t.urgency_hint}</span><small>{t.district||'Jharkhand'} · {t.category||'Uncategorised'}</small></div><strong>{t.title}</strong><span className="ticket-status">{label(t.status)}</span></button>)}{tickets.length===0&&<div className="empty">No tickets in the queue.</div>}</aside><article className="ticket-detail">{selected?<><div className="detail-top"><div><div className="hero-kicker">TICKET</div><h2>{selected.title}</h2><p>{selected.description}</p><div className="detail-meta">{selected.category} · {selected.request_type} · {selected.district||'Location not supplied'}{selected.block?` · ${selected.block}`:''}</div></div><div className="detail-actions"><button className="secondary-btn" disabled={busy} onClick={()=>moderate(selected.id,'HIDDEN')}>Hide</button><button className="secondary-btn" disabled={busy} onClick={()=>moderate(selected.id,'VISIBLE')}>Restore</button></div></div><div className="detail-grid"><div><span>Reporter</span><strong>{selected.citizen_name||'Private citizen'}</strong></div><div><span>Urgency</span><strong>{selected.urgency_hint}</strong></div><div><span>Status</span><strong>{label(current)}</strong></div><div><span>Reported</span><strong>{new Date(selected.created_at).toLocaleDateString()}</strong></div></div><div className="admin-card"><h3>Government inspection</h3><p>Review the AI category, accepted request type, matched institutions, project lifecycle and moderation history through the linked platform records.</p></div></>:<div className="empty large-empty">Select a ticket to inspect its progress.</div>}</article></div>}
  {tab==='overview'&&<div className="admin-overview"><div className="admin-card"><h3>District load</h3>{(data.districts||[]).map((d:any)=><div className="admin-bar" key={d.district}><span>{d.district}</span><div><i style={{width:`${Math.max(4,Math.round(d.challenges/Math.max(1,...(data.districts||[]).map((x:any)=>x.challenges))*100))}%`}}/></div><b>{d.challenges}</b></div>)}</div><div className="admin-card"><h3>Impact</h3><div className="big-metrics"><div><b>{data.impact.people_affected}</b><span>People affected</span></div><div><b>{data.impact.villages_affected}</b><span>Villages affected</span></div><div><b>{data.impact.time_saved_hours}</b><span>Hours saved</span></div></div></div></div>}
  {tab==='organizations'&&<div className="partner-grid">{(data.organizations||[]).map((o:any)=><article className="partner-card" key={o.id}><div className="partner-top"><span className={o.verified?'verified':'unverified'}>{o.verified?'VERIFIED':'REVIEW'}</span><small>{label(o.organization_type)}</small></div><h3>{o.name}</h3><p>{o.description||'No description provided.'}</p><div className="partner-stats"><span><b>{o.average_rating||0}</b> rating</span><span><b>{o.rating_count||0}</b> reviews</span><span><b>{o.member_count||0}</b> members</span></div><button className="secondary-btn" disabled={busy} onClick={()=>verify(o.id,!o.verified)}>{o.verified?'Revoke verification':'Verify partner'}</button></article>)}</div>}
  {tab==='projects'&&<div className="admin-card"><div className="account-list">{governmentProjects.map((p:any)=><div className="account-row" key={p.id}><div><strong>{p.title}</strong><span>{p.organization_name} · {p.challenge_title} · {label(p.status)}</span><span>{p.district||'District not supplied'} · {p.member_count} active members · {p.update_count} updates</span></div><span className={p.challenge_status==='RESOLVED'?'verified':'unverified'}>{label(p.challenge_status)}</span></div>)}{governmentProjects.length===0&&<div className="empty">No projects found.</div>}</div></div>}
  {tab==='accounts'&&<div className="admin-card"><div className="account-list">{(data.adminUsers||[]).map((u:any)=><div className="account-row" key={u.id}><div><strong>{u.full_name}</strong><span>{label(u.role)} · {u.email}{u.organization_name?` · ${u.organization_name}`:''}</span></div><div><span className={u.active?'verified':'unverified'}>{u.active?'ACTIVE':'INACTIVE'}</span><button className="secondary-btn small" disabled={busy} onClick={()=>setAccount(u.id,!u.active)}>{u.active?'Deactivate':'Activate'}</button></div></div>)}{(data.adminUsers||[]).length===0&&<div className="empty">No administrative accounts found.</div>}</div></div>}
  {showOrg&&<div className="modal-backdrop"><form className="modal-card" onSubmit={createOrg}><div className="modal-head"><div><div className="hero-kicker">ONBOARDING</div><h2>Add institution</h2><p>Government-created institutions are active immediately and can participate in SmartSolve matching.</p></div><button type="button" className="ghost-btn" onClick={()=>setShowOrg(false)}>×</button></div><div className="field-grid"><label>Institution name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Type<select value={form.organizationType} onChange={e=>setForm({...form,organizationType:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Description<textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="field-grid"><label>District<select value={form.district} onChange={e=>setForm({...form,district:e.target.value})}><option value="">Select district</option>{districts.map(x=><option key={x}>{x}</option>)}</select></label><label>Address<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label></div><div className="field-grid"><label>Latitude<input type="number" step="any" value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})}/></label><label>Longitude<input type="number" step="any" value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})}/></label></div><label>Accepted problem areas<input value={form.categories} onChange={e=>setForm({...form,categories:e.target.value})} placeholder="water-resources, environment, education"/></label><label>Expertise<input value={form.expertise} onChange={e=>setForm({...form,expertise:e.target.value})} placeholder="civil-engineering, software, GIS"/></label><label>Accepted work types<input value={form.requestTypes} onChange={e=>setForm({...form,requestTypes:e.target.value})} placeholder="student-project, research-project, implementation"/></label><label className="check"><input type="checkbox" checked={form.verified} onChange={e=>setForm({...form,verified:e.target.checked})}/> Mark as verified</label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={()=>setShowOrg(false)}>Cancel</button><button className="primary-btn" disabled={busy}>{busy?'Creating…':'Create institution'}</button></div></form></div>}
  {showUser&&<div className="modal-backdrop"><form className="modal-card" onSubmit={createUser}><div className="modal-head"><div><div className="hero-kicker">ACCESS CONTROL</div><h2>Create administrator</h2><p>Only authorized Government or Super Admin users can provision privileged accounts.</p></div><button type="button" className="ghost-btn" onClick={()=>setShowUser(false)}>×</button></div><div className="field-grid"><label>Full name<input required value={userForm.fullName} onChange={e=>setUserForm({...userForm,fullName:e.target.value})}/></label><label>Role<select value={userForm.role} onChange={e=>setUserForm({...userForm,role:e.target.value})}><option value="GOVERNMENT">Government</option><option value="ORGANIZATION_ADMIN">Organization Admin</option><option value="SUPER_ADMIN">Super Admin</option></select></label></div><div className="field-grid"><label>Email<input required type="email" value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})}/></label><label>Temporary password<input required type="password" minLength={12} value={userForm.password} onChange={e=>setUserForm({...userForm,password:e.target.value})}/></label></div>{userForm.role==='ORGANIZATION_ADMIN'&&<label>Organization<select required value={userForm.organizationId} onChange={e=>setUserForm({...userForm,organizationId:e.target.value})}><option value="">Select organization</option>{(data.organizations||[]).map((o:any)=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}<label>Phone<input value={userForm.phone} onChange={e=>setUserForm({...userForm,phone:e.target.value})}/></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={()=>setShowUser(false)}>Cancel</button><button className="primary-btn" disabled={busy}>{busy?'Creating…':'Create trusted account'}</button></div></form></div>}
 </section>
}
